flask-marketplace/marketplace/app/blueprints/marketplace/forms.py
from flask_uploads import UploadSet, IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, MultipleFileField, TextAreaField, BooleanField, IntegerField, FloatField, SubmitField, \
    RadioField, SelectField
from wtforms.validators import InputRequired, Length, Email, Optional
from wtforms_alchemy import QuerySelectMultipleField, QuerySelectField, Unique, model_form_factory
from wtforms.fields.html5 import EmailField

from app import db
from app.models import MBrand, MVariant, MCategory, MCurrency, User
from app.utils import states, countries, conditions

images = UploadSet('images', IMAGES)
BaseModelForm = model_form_factory(FlaskForm)

class SVariantForm(FlaskForm):
    name = StringField('Variant name...', validators=[InputRequired()])
    symbol = StringField('Variant Symbol...', validators=[InputRequired()])
    submit = SubmitField('Submit')

class ReviewForm(FlaskForm):
    message = StringField('Write your review...', validators=[InputRequired()])
    score = FloatField('Score from 0 to 5', validators=[InputRequired()])
    submit = SubmitField('Submit')

class SearchForm(FlaskForm):
    query = StringField('Search...', validators=[InputRequired(), Length(1, 64)])


class SProductForm(FlaskForm):
    name = StringField('Product name', validators=[InputRequired(), Length(1, 64)])
    images = MultipleFileField('Product Images', validators=[InputRequired(), FileAllowed(images, 'Images only!')])
    description = TextAreaField('Description', [InputRequired()])
    categories = QuerySelectMultipleField(
        'Categories',
        validators=[InputRequired()],
        get_label='name',
        query_factory=lambda: db.session.query(MCategory).order_by('order')
    )
    #variants = QuerySelectMultipleField(
       # 'Variants',
        #validators=[InputRequired()],
        # get_label='name',
        #query_factory=lambda: db.session.query(MVariant).order_by('name')
    #)
    condition = SelectField(u'Select condition', choices=conditions)
    availability = BooleanField(u'Is it currently available?')
    min_order_quantity = IntegerField('Min number of units per order e.g 1', default=1)
    length = FloatField('Length in numbers only e.g 0.99')
    weight = FloatField('Weight in numbers only e.g 0.21')
    height = FloatField('Height in numbers only e.g 10')
    price = FloatField('Price, Figures only e.g 16.99')
    price_currency = QuerySelectField(
        'Price currency',
        validators=[InputRequired()],
        get_label='name',
        query_factory=lambda: db.session.query(MCurrency).order_by('name'))
    brand = QuerySelectField(
        'Brand',
        validators=[Optional()],
        get_label='name',
        query_factory=lambda: db.session.query(MBrand).order_by('name'))
    is_featured = BooleanField("Is Featured ?")
    lead_time = StringField('Delivery time')
    submit = SubmitField('Submit')


class SShippingForm(FlaskForm):
    first_name = StringField('First name', validators=[InputRequired()])
    last_name = StringField('Last name', validators=[InputRequired()])
    email = EmailField('Email', validators=[InputRequired(), Email()])
    mobile_phone = IntegerField('Phone numbers only', validators=[InputRequired()])
    state = StringField('State', validators=[InputRequired()])
    zip = StringField('Zip Code', validators=[InputRequired(), Length(1, 7)])
    country = SelectField(u'Select Country', choices=countries)
    city = StringField('City', validators=[InputRequired()])


class SShippingMethodForm(FlaskForm):
    name = StringField('Name', validators=[InputRequired()])
    submit = SubmitField('Submit')

flask-marketplace/marketplace/app/blueprints/marketplace/__init__.py
from app.blueprints.marketplace.views import marketplace  # noqa
from app.blueprints.marketplace import errors  # noqa

flask-marketplace/marketplace/app/blueprints/marketplace/views.py
import os
import datetime
import json
import math

import stripe
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, abort, make_response
from flask_jwt_extended import decode_token, create_access_token
from flask_login import login_required
from flask_rq import get_queue
from flask_uploads import UploadSet, IMAGES
from flask_wtf.file import FileAllowed
from sqlalchemy import Date
from sqlalchemy.orm import contains_eager, joinedload
from wtforms import Flags

from app import db
from app.blueprints.marketplace.forms import ReviewForm, SearchForm, SVariantForm, SProductForm, SShippingForm, SShippingMethodForm
from app.blueprints.admin.forms import *
from app.blueprints.marketplace.apis import *
from app.blueprints.api import main_api
from app.blueprints.marketplace.paystack import Paystack
from app.decorators import seller_required, buyer_required, anonymous_required
from app.email import send_email
from app.models import MProduct, MProductCategory, MCategory, MBanner, MReview, MVariant, current_user, User, MShippingMethod, MCartDetails, MSettings, MCurrency, \
    MShippingMethodPrice, MOrderItem, MOrder, MSellerOrder, LandingSetting, MBrand, BackgroundImage, SiteLogo

marketplace = Blueprint('marketplace', __name__)
images = UploadSet('images', IMAGES)


# stripe secret key
stripe_secret = os.environ.get(
    'STRIPE_SECRET') 




# Marketplace Shopping Routes start
@marketplace.route('/')
def index():
    form = SearchForm()
    banner = MBanner.query.first()
    background = BackgroundImage.query.first()
    logo = SiteLogo.query.first()
    settings = LandingSetting.query.all()
    website_settings = MSettings.query.first()
    brands = MBrand.query.order_by(MBrand.created_at.asc()).limit(5).all()
    featured_products = MProduct.query.filter_by(availability=True).filter_by(
        is_featured=True).order_by(MProduct.created_at.asc()).limit(4).all()  # .limit(5).all()
    new_arrived_products = MProduct.query.filter_by(
        availability=True).order_by(MProduct.created_at.desc()).limit(4).all()
    categories_instances = MCategory.query.filter_by(is_featured=True).all()
    return render_template('marketplace/landing-page.html', form=form, categories=categories_instances, featured_products=featured_products,
                           new_arrived_products=new_arrived_products, settings=settings, website_settings=website_settings, brands=brands, banner=banner,
                           background=background, logo=logo)


@marketplace.route('/review', methods=['POST'])
def review():
    product_id = int(request.form.get('product_id'))
    product_name = request.form.get('product_name')
    review_text = request.form.get('review_text')
    review_rating = float(request.form.get('review_rating'))
    product_instance = MProduct.query.get_or_404(product_id)
    review = MReview(message=review_text, score=review_rating,
                     user=current_user, product=product_instance)
    db.session.add(review)
    db.session.commit()
    return {
        "status": 1
    }

#'''
# This view is not really necessary.
@marketplace.route('/categories')
def categories():
    categories_list = MCategory.query.filter_by(parent_id=None).all()
    website_settings = MSettings.query.first()
    return render_template('marketplace/categories/index.html', website_settings=website_settings, categories=categories_list)
#'''

@marketplace.route('/category/<int:category_id>/<category_name>', defaults={'page': 1}, methods=['GET'])
@marketplace.route('/category/<int:category_id>/<category_name>/<int:page>', methods=['GET'])
@marketplace.route('/category/<int:category_id>/<category_name>/<int:page>', methods=['GET'])
def category(page, category_id, category_name):
    products = MProduct.query.join(MProductCategory).filter(
        MProductCategory.category_id == category_id).paginate(page, per_page=8)
    website_settings = MSettings.query.first()
    return render_template('marketplace/categories/category.html', website_settings=website_settings, category_id=category_id, category_name=category_name, products=products)


@marketplace.route('/product/<int:product_id>/<product_name>')
def product(product_id, product_name):
    product_instance = db.session.query(MProduct).filter(
        MProduct.id == product_id).options(joinedload(MProduct.variants)).first()
    product_variants = product_instance.variants
    review_form = ReviewForm()
    # print(current_user.name)
    if current_user.is_authenticated:
        current_user_review = MReview.query.filter_by(
            user=current_user).filter_by(product=product_instance).first()
    website_settings = MSettings.query.first()
    # if current_user.is_authenticated and current_user.is_seller:
    #     can_review = False
    # elif current_user.is_authenticated and current_user_review:
    #     can_review = False
    # elif current_user.is_authenticated and not current_user_review:
    #     can_review = True
    # else:
    #     can_review = False
    can_review = True if current_user.is_authenticated and not current_user_review else False

    settings = LandingSetting.query.all()
    return render_template('marketplace/products/product.html', website_settings=website_settings, review_form=review_form,
                           can_review=can_review, product_instance=product_instance, settings=settings)


@marketplace.route('/seller/<int:seller_id>/products')
def view_seller_products(seller_id):
    seller = User.query.filter_by(id=seller_id).filter_by(
        is_seller=True).first_or_404()
    avail_products = MProduct.query.filter_by(
        seller=seller).filter_by(availability=True).all()
    not_avail_products = MProduct.query.filter_by(
        seller=seller).filter_by(availability=False).all()
    website_settings = MSettings.query.first()
    return render_template('marketplace/products/seller.html', website_settings=website_settings, avail_products=avail_products,
                           not_avail_products=not_avail_products)


@marketplace.route('/cart')
def cart():
    cart_instance = get_current_cart()
    website_settings = MSettings.query.first()
    if cart_instance.products_count == 0:
        cart_instance.step = 1
        return render_template('marketplace/cart/no_items.html', website_settings=website_settings)
    if cart_instance.step != 1:
        return redirect(url_for('marketplace.order', step=cart_instance.step))
    return render_template('marketplace/cart/index.html', website_settings=website_settings, cart=cart_instance)


@marketplace.route('/order/<int:step>', methods=['GET', 'POST'])
def order(step):
    cart_instance = get_current_cart()
    website_settings = MSettings.query.first()
    if cart_instance.products_count == 0:
        cart_instance.step = 1
        return render_template('marketplace/cart/no_items.html', website_settings=website_settings)

    if request.method == 'POST':
        if step == 1:
            cart_instance.step = 1
            return redirect(url_for('marketplace.cart'))

        elif step == 2:
            print("Enter your details")
            if cart_instance.step == 1:
                for item in cart_instance.cart_items:
                    product_instance = item.product
                    if item.count < product_instance.min_order_quantity:
                        flash("You cannot buy less than {} pieces of the product {}".format(
                            product_instance.min_order_quantity, product_instance.name), 'error')
                        return redirect(url_for('marketplace.cart'))
                cart_instance.step = 2
                return redirect(url_for('marketplace.order', step=2))

            if cart_instance.step == 3:
                cart_instance.step = 2
                MCartDetails.query.filter_by(cart=cart_instance).delete()
                items = MCartItem.query.filter_by(cart=cart_instance).all()
                for item in items:
                    item.shipping_method = None
                    db.session.add(item)
                db.session.commit()
                return redirect(url_for('marketplace.order', step=2))

            if cart_instance.step == 2:
                return redirect(url_for('marketplace.order', step=2))

        elif step == 3:
            print("Now enter your stripe")
            form = SShippingForm()
            valid = True
            for seller_cart in cart_instance.seller_carts:
                input_field = "shipping[{}]".format(seller_cart.seller.id)
                val = request.form.get(input_field)
                if not val:
                    valid = False
                    form.errors[input_field] = ['This Field is Required']
                elif not MShippingMethod.query.get(val):
                    form.errors[input_field] = [
                        'Not A Valid Choice, Pls Try Again']
                    valid = False
            if not current_user.is_authenticated:
                user = User.query.filter_by(email=form.email.data).first()
                if user:
                    flash(
                        'There is a mediville user with this email, choose another email or login instead', 'error')
                    valid = False
            if not valid:
                form.process(request.form)
                return render_template('marketplace/cart/order_shipping.html', cart=cart_instance, form=form, website_settings=website_settings)

            if form.validate_on_submit():
                cart_details = MCartDetails(
                    cart=cart_instance,
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    email=form.email.data,
                    mobile_phone=form.mobile_phone.data,
                    state=form.state.data,
                    zip=form.zip.data,
                    country=form.country.data,
                    city=form.city.data,
                )

flask-marketplace/marketplace/app/templates/marketplace/products/product.html
{% extends 'layouts/base.html' %}
{% import 'macros/product_macros.html' as products_macros %}
{% import 'macros/product_detail_macros.html' as p %}
{% block page_title %}
    {{ product_instance.name }}
{% endblock %}

{% block custom_head_tags %}
   <meta name="description" content="{{ product_instance.description }}">
    <!-- jQuery -->
    <script src="{{ url_for('static', filename='js/jquery-2.0.0.min.js') }}"></script>
    
    <!-- Bootstrap4 files-->
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
    <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet"/>

    <!-- Font awesome 5 -->
    <link href="{{ url_for('static', filename='fonts/all.min.css') }}" rel="stylesheet">

    <!-- plugin: fancybox  -->
    <script src="{{ url_for('static', filename='plugins/fancybox/fancybox.min.js') }}" ></script>
    <link href="{{ url_for('static', filename='plugins/fancybox/fancybox.min.css') }}"  rel="stylesheet">

    <!-- custom style -->
    <link href="{{ url_for('static', filename='css/ui.css') }}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='css/custom_responsive.css') }}" rel="stylesheet" media="only screen and (max-width: 1200px)" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        /* Rating Star Widgets Style */
        .rating-stars ul {
        list-style-type:none;
        padding:0;
        
        -moz-user-select:none;
        -webkit-user-select:none;
        }
        .rating-stars ul > li.star {
        display:inline-block;
        
        }

        /* Idle State of the stars */
        .rating-stars ul > li.star > i.fa {
        font-size:1.5em; /* Change the size of the stars */
        color:#ccc; /* Color on idle state */
        }

        /* Hover state of the stars */
        .rating-stars ul > li.star.hover > i.fa {
        color:#FFCC36;
        }

        /* Selected state of the stars */
        .rating-stars ul > li.star.selected > i.fa {
        color:#FF912C;
        }
    </style>
{% endblock %}
{% block content %}
    
<!-- ============================ COMPONENT 1 ================================= -->
<div class="container">
    {{ p.product_detail(product_instance) }}

<!-- ============================ COMPONENT 1 END .// ================================= -->
    <!-- <hr> -->
<!-- ============================ REVIEW START .// ================================= -->
    <div class="mt-3">
        <h3><strong>Reviews: </strong></h3>
        {% for review in product_instance.reviews %}
            {{ products_macros.review_wid(review) }}
        {% endfor %} 
        {% if product_instance.reviews | length == 0 %}
        <p class="ml-3">No Review yet</p>
        {% endif %}
        {% if can_review %}
            {{ products_macros.review_form(review_form, product_instance) }}
        {% endif %}
    </div>
<!-- ============================ REVIEW END .// ================================= -->
    <!-- <hr> -->
<!-- ============================ CATEGORY START .// ================================= -->
    <div class="mt-3">
        <h3><strong>Categories: </strong></h3>
        {% for category in product_instance.categories %}
            {{ products_macros.category_wid(category) }}
        {% endfor %}
    </div>
<!-- ============================ CATEGORY END .// ================================= -->
</div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='lightbox/js/lightbox.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.slick').slick({
                infinite: false,
            });
        });

    </script>
    <script>
         $('#add-to-cart').click(function () {
            let variant_id = $('input[type="radio"]:checked').val();
            let product_id = $('input[type="radio"]:checked').data('product-id');
            let quantityInput = $('#quantity');
            let quantityVal = parseInt(quantityInput.val());
            // alert(`variant id is ${variant_value}, product id is ${product_value}, quantity is ${quantityVal}`);
            addToCart(product_id, variant_id, quantityVal);
        });
        $('#buy-now').click(function () {
            let variant_id = $('input[type="radio"]:checked').val();
            let product_id = $('input[type="radio"]:checked').data('product-id');
            let quantityInput = $('#quantity');
            let quantityVal = parseInt(quantityInput.val());
            // alert(`variant id is ${variant_value}, product id is ${product_value}, quantity is ${quantityVal}`);
            BuyNow(product_id, variant_id, quantityVal);
        });
        $('#increase-quantity').click(function () {
            let quantityInput = $('#quantity');
            let quantityVal = parseInt(quantityInput.val());
            quantityInput.val(quantityVal + 1);
        });
        $('#decrease-quantity').click(function () {
            let quantityInput = $('#quantity');
            let quantityVal = parseInt(quantityInput.val());
            if(quantityVal > 1) {
                quantityInput.val(quantityVal - 1);
            }
        });

        /* 1. Visualizing things on Hover - See next part for action on click */
        $('#stars li').on('mouseover', function(){
            var onStar = parseInt($(this).data('value'), 10); // The star currently mouse on
        
            // Now highlight all the stars that's not after the current hovered star
            $(this).parent().children('li.star').each(function(e){
            if (e < onStar) {
                $(this).addClass('hover');
            }
            else {
                $(this).removeClass('hover');
            }
            });
            
        }).on('mouseout', function(){
            $(this).parent().children('li.star').each(function(e){
            $(this).removeClass('hover');
            });
        });
        
        
        /* 2. Action to perform on click */
        $('#stars li').on('click', function(){
            var onStar = parseInt($(this).data('value'), 10); // The star currently selected
            var stars = $(this).parent().children('li.star');
            
            for (i = 0; i < stars.length; i++) {
            $(stars[i]).removeClass('selected');
            }
            
            for (i = 0; i < onStar; i++) {
            $(stars[i]).addClass('selected');
            }
            
            // JUST RESPONSE (Not needed)
            var ratingValue = parseInt($('#stars li.selected').last().data('value'), 10);
            var msg = "";
            if (ratingValue > 1) {
                msg = "Thanks! You rated this " + ratingValue + " stars.";
            }
            else {
                msg = "We will improve ourselves. You rated this " + ratingValue + " stars.";
            }
            console.log(msg);
            
        });
    </script>
    <script>
        $('#review-form').submit(function(e){
            e.preventDefault();
            let review_rating = parseInt($('#stars li.selected').last().data('value'), 10) * 20;
            let review_text = $('#review-text').val();
            let product_id = $('#review-text').data('product-id');
            let product_name = $('#review-text').data('product-name');
            console.log("product_id", product_id)
            console.log("product_name", product_name)
            let data = new FormData();
            data.set('csrf_token', "{{ csrf_token()  }}");
            data.set('product_id', product_id);
            data.set('product_name', product_name);
            data.set('review_text', review_text);
            data.set('review_rating', review_rating);
            axios.post('{{ url_for("marketplace.review") }}', data )
                .then(function (response) {
                    if(response.data.status === 1) {
                        location.reload();
                    }
                    console.log(response)
                });
            });
    </script>
{% endblock %}

flask-marketplace/marketplace/app/templates/marketplace/products/test_product.html
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description"
          content="{% for setting in settings %}{{setting.site_name}}{% endfor %} : {{ product_instance.name }}, {{ product_instance.description }}">
<meta name="author" content="{% for setting in settings %}{{setting.site_name}}{% endfor %}{ setting.site_name }}">
<meta name="og:title" content="{% for setting in settings %}{{setting.site_name}}{% endfor %} - {{ product_instance.name }}"/>
<meta name="og:type" content="website"/>
<meta name="og:url" content="{{ url_for('marketplace.product', product_id=product_instance.id, product_name=product_instance.name,_external=True) }}"/>
    {% if json_load(product_instance.images) | length %}
        <meta property="og:image"              content="{{ url_for('_uploads.uploaded_file', setname='images',
                           filename=json_load(product_instance.images)[0] , _external=True) }}" />
    {% endif %}
<meta name="og:site_name" content="{% for setting in settings %}{{setting.site_name}}{% endfor %} : {{ product_instance.name }}, {{ product_instance.description }}"/>
<meta name="og:description"
          content="{% for setting in settings %}{{setting.site_name}}{% endfor %} : {{ product_instance.name }}, {{ product_instance.description }}"/>
<meta name="twitter:card" content="summary"/>
<meta name="twitter:site" content="@{% for setting in settings %}{{setting.site_name}}{% endfor %}"/>
<meta name="twitter:creator" content="@anioko1"/>
<meta property="og:url" content="{{ url_for('marketplace.product', product_id=product_instance.id, product_name=product_instance.name,_external=True) }}"/>
<meta property="og:title" content="{% for setting in settings %}{{setting.site_name}}{% endfor %} - {{ product_instance.name }}"/>
<meta property="og:description"
          content="{% for setting in settings %}{{setting.site_name}}{% endfor %} : {{ product_instance.name }}, {{ product_instance.description }}"/>
    {% if json_load(product_instance.images) | length %}
        <meta property="og:image"              content="{{ url_for('_uploads.uploaded_file', setname='images',
                           filename=json_load(product_instance.images)[0] , _external=True) }}" />
    {% endif %}

<link href="{{ url_for('static', filename='frontend/images/favicon.ico') }}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{{ url_for('static', filename='frontend/js/jquery-2.0.0.min.js') }}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{{ url_for('static', filename='frontend/js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
<link href="{{ url_for('static', filename='frontend/css/bootstrap.css') }}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{{ url_for('static', filename='frontend/fonts/fontawesome/css/all.min.css') }}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{{ url_for('static', filename='frontend/css/ui.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ url_for('static', filename='frontend/css/responsive.css') }}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{{ url_for('static', filename='frontend/js/script.js') }}" type="text/javascript"></script>



<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>
{% for setting in settings %}
{{setting.other_tracking_analytics_one|safe}}
{{setting.other_tracking_analytics_two|safe}}
{{setting.other_tracking_analytics_three|safe}}
{{setting.other_tracking_analytics_four|safe}}
{% endfor %}
</head>

<body>

<header class="section-header">
<section class="header-main">
<div class="container">
	<a href="http://bootstrap-ecommerce.com" class="brand-wrap"><img class="logo" src="../images/logo.png"></a>
</div> <!-- container.// -->
</section>
</header> <!-- section-header.// -->


<section class="section-content padding-y bg">
<div class="container">
<div class="card">
	<div class="row no-gutters">
		<aside class="col-md-6">
<article class="gallery-wrap">
<div class="img-big-wrap">
{% for image in json_load(product_instance.images) %}
  <div> <a href="#"><img src="{{ url_for('_uploads.uploaded_file', setname='images',
                           filename=json_load(product_instance.images)[0] , _external=True) }}"></a></div> 
						   {% endfor %}
</div> <!-- slider-product_instance.// -->
<!----comment out this to use in adding mutiple images for the product ---->
<!---<div class="thumbs-wrap"> 
  <a href="#" class="item-thumb"> <img src="bootstrap-ecommerce-html/images/items/12.jpg"></a>
  <a href="#" class="item-thumb"> <img src="bootstrap-ecommerce-html/images/items/12-1.jpg"></a>
  <a href="#" class="item-thumb"> <img src="bootstrap-ecommerce-html/images/items/12-2.jpg"></a>
</div> <!-- slider-nav.// -->
</article> <!-- gallery-wrap .end// -->
		</aside>
		<main class="col-md-6 border-left">
<article class="content-body">

<h2 class="title">{{ product_instance.name }}</h2>

<!----comment out this to use to add ratings ---->
<!----<div class="rating-wrap my-3">
	<ul class="rating-stars">
		<li style="width:80%" class="stars-active">
			<i class="fa fa-star"></i> <i class="fa fa-star"></i>
			<i class="fa fa-star"></i> <i class="fa fa-star"></i>
			<i class="fa fa-star"></i>
		</li>
		<li>
			<i class="fa fa-star"></i> <i class="fa fa-star"></i>
			<i class="fa fa-star"></i> <i class="fa fa-star"></i>
			<i class="fa fa-star"></i>
		</li>
	</ul>
	<small class="label-rating text-muted">132 reviews</small>
	<small class="label-rating text-success"> <i class="fa fa-clipboard-check"></i> 154 orders </small>
</div> <!-- rating-wrap.// -->

<div class="mb-3">
	<var class="price h4">{{ product_instance.price_currency.symbol }}{{ product_instance.price }}</var>
	<span class="text-muted">/per kg</span>
</div> <!-- price-detail-wrap .// -->

<p>{{ product_instance.description }}</p>


<dl class="row">
  <dt class="col-sm-3">Minimum Order Quantity</dt>
  <dd class="col-sm-9">{{ product_instance.min_order_quantity }}</dd>

  <dt class="col-sm-3">Weight</dt>
  <dd class="col-sm-9">{{ product_instance.weight }}</dd>
  
  <dt class="col-sm-3">Delivery Lead Time in Days</dt>
  <dd class="col-sm-9">{{ product_instance.lead_time }}</dd>
 
  <dt class="col-sm-3">Delivery Time in Days</dt>
  <dd class="col-sm-9">{{ product_instance.deliver_time }}</dd>
  
  <dt class="col-sm-3">Length | Height</dt>
  <dd class="col-sm-9"> {% if product_instance.length %} 
   {{ product_instance.length ~ "|" }} {{ product_instance.height }}  
   {% else %} 
   None sepecified ! 
      {% endif %} 
  </dd>


  <dt class="col-sm-3">Seller</dt>
  <dd class="col-sm-9">{{ product_instance.seller.full_name }}</dd> <!--add link to seller public profile -->
  
</dl>

<hr>
<!----comment out this to use to add quantity ---->
	<div class="form-row">
		<!---<div class="form-group col-md flex-grow-0">
			<label>Quantity</label>
			<div class="input-group mb-3 input-spinner">
			  <div class="input-group-prepend">
			    <button class="btn btn-light" type="button" id="button-plus"> + </button>
			  </div>
			  <input type="text" class="form-control" value="1">
			  <div class="input-group-append">
			    <button class="btn btn-light" type="button" id="button-minus"> − </button>
			  </div>
			</div>
		</div> <!-- col.// -->
		<!----comment out this to use to add size selection ---->
		<!---<div class="form-group col-md">
				<label>Select size</label>
				<div class="mt-1">
					<label class="custom-control custom-radio custom-control-inline">
					  <input type="radio" name="select_size" checked="" class="custom-control-input">
					  <div class="custom-control-label">Small</div>
					</label>

					<label class="custom-control custom-radio custom-control-inline">
					  <input type="radio" name="select_size" class="custom-control-input">
					  <div class="custom-control-label">Medium</div>
					</label>

					<label class="custom-control custom-radio custom-control-inline">
					  <input type="radio" name="select_size" class="custom-control-input">
					  <div class="custom-control-label">Large</div>
					</label>

				</div>
		</div> <!-- col.// -->
	</div> <!-- row.// -->
{% if product_instance.availability %} 	
	{% include 'partials/_chart_and_buy_buttons.html' %}

                    {% else %}
   <dt class="col-sm-3">Out of Stock</dt>
                    {% endif %}
</article> <!-- product-info-aside .// -->
		</main> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- card.// -->
{% if request.blueprint == 'marketplace' %}
    {% include 'marketplace/partials/scripts.html' %}
{% endif %}
</body>
</html>