flask-marketplace/marketplace/app/blueprints/marketplace/forms.py
from flask_uploads import UploadSet, IMAGES
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, MultipleFileField, TextAreaField, BooleanField, IntegerField, FloatField, SubmitField, \
    RadioField, SelectField
from wtforms.validators import InputRequired, Length, Email, Optional
from wtforms_alchemy import QuerySelectMultipleField, QuerySelectField, Unique, model_form_factory
from wtforms.fields.html5 import EmailField

from app import db
from app.models import MBrand, MVariant, MCategory, MCurrency, User
from app.utils import states, countries, conditions

images = UploadSet('images', IMAGES)
BaseModelForm = model_form_factory(FlaskForm)

class SVariantForm(FlaskForm):
    name = StringField('Variant name...', validators=[InputRequired()])
    symbol = StringField('Variant Symbol...', validators=[InputRequired()])
    submit = SubmitField('Submit')

class ReviewForm(FlaskForm):
    message = StringField('Write your review...', validators=[InputRequired()])
    score = FloatField('Score from 0 to 5', validators=[InputRequired()])
    submit = SubmitField('Submit')

class SearchForm(FlaskForm):
    query = StringField('Search...', validators=[InputRequired(), Length(1, 64)])


class SProductForm(FlaskForm):
    name = StringField('Product name', validators=[InputRequired(), Length(1, 64)])
    images = MultipleFileField('Product Images', validators=[InputRequired(), FileAllowed(images, 'Images only!')])
    description = TextAreaField('Description', [InputRequired()])
    categories = QuerySelectMultipleField(
        'Categories',
        validators=[InputRequired()],
        get_label='name',
        query_factory=lambda: db.session.query(MCategory).order_by('order')
    )
    #variants = QuerySelectMultipleField(
       # 'Variants',
        #validators=[InputRequired()],
        # get_label='name',
        #query_factory=lambda: db.session.query(MVariant).order_by('name')
    #)
    condition = SelectField(u'Select condition', choices=conditions)
    availability = BooleanField(u'Is it currently available?')
    min_order_quantity = IntegerField('Min number of units per order e.g 1', default=1)
    length = FloatField('Length in numbers only e.g 0.99')
    weight = FloatField('Weight in numbers only e.g 0.21')
    height = FloatField('Height in numbers only e.g 10')
    price = FloatField('Price, Figures only e.g 16.99')
    price_currency = QuerySelectField(
        'Price currency',
        validators=[InputRequired()],
        get_label='name',
        query_factory=lambda: db.session.query(MCurrency).order_by('name'))
    brand = QuerySelectField(
        'Brand',
        validators=[Optional()],
        get_label='name',
        query_factory=lambda: db.session.query(MBrand).order_by('name'))
    is_featured = BooleanField("Is Featured ?")
    lead_time = StringField('Delivery time')
    submit = SubmitField('Submit')


class SShippingForm(FlaskForm):
    first_name = StringField('First name', validators=[InputRequired()])
    last_name = StringField('Last name', validators=[InputRequired()])
    email = EmailField('Email', validators=[InputRequired(), Email()])
    mobile_phone = IntegerField('Phone numbers only', validators=[InputRequired()])
    state = StringField('State', validators=[InputRequired()])
    zip = StringField('Zip Code', validators=[InputRequired(), Length(1, 7)])
    country = SelectField(u'Select Country', choices=countries)
    city = StringField('City', validators=[InputRequired()])


class SShippingMethodForm(FlaskForm):
    name = StringField('Name', validators=[InputRequired()])
    submit = SubmitField('Submit')

flask-marketplace/marketplace/app/blueprints/marketplace/__init__.py
from app.blueprints.marketplace.views import marketplace  # noqa
from app.blueprints.marketplace import errors  # noqa

flask-marketplace/marketplace/app/blueprints/marketplace/views.py
import os
import datetime
import json
import math

import stripe
from flask import Blueprint, render_template, request, flash, redirect, url_for, session, abort, make_response
from flask_jwt_extended import decode_token, create_access_token
from flask_login import login_required
from flask_rq import get_queue
from flask_uploads import UploadSet, IMAGES
from flask_wtf.file import FileAllowed
from sqlalchemy import Date
from sqlalchemy.orm import contains_eager, joinedload
from wtforms import Flags

from app import db
from app.blueprints.marketplace.forms import ReviewForm, SearchForm, SVariantForm, SProductForm, SShippingForm, SShippingMethodForm
from app.blueprints.admin.forms import *
from app.blueprints.marketplace.apis import *
from app.blueprints.api import main_api
from app.blueprints.marketplace.paystack import Paystack
from app.decorators import seller_required, buyer_required, anonymous_required
from app.email import send_email
from app.models import MProduct, MProductCategory, MCategory, MBanner, MReview, MVariant, current_user, User, MShippingMethod, MCartDetails, MSettings, MCurrency, \
    MShippingMethodPrice, MOrderItem, MOrder, MSellerOrder, LandingSetting, MBrand, BackgroundImage, SiteLogo

marketplace = Blueprint('marketplace', __name__)
images = UploadSet('images', IMAGES)


# stripe secret key
stripe_secret = os.environ.get(
    'STRIPE_SECRET') 




# Marketplace Shopping Routes start
@marketplace.route('/')
def index():
    form = SearchForm()
    banner = MBanner.query.first()
    background = BackgroundImage.query.first()
    logo = SiteLogo.query.first()
    settings = LandingSetting.query.all()
    website_settings = MSettings.query.first()
    brands = MBrand.query.order_by(MBrand.created_at.asc()).limit(5).all()
    featured_products = MProduct.query.filter_by(availability=True).filter_by(
        is_featured=True).order_by(MProduct.created_at.asc()).limit(4).all()  # .limit(5).all()
    new_arrived_products = MProduct.query.filter_by(
        availability=True).order_by(MProduct.created_at.desc()).limit(4).all()
    categories_instances = MCategory.query.filter_by(is_featured=True).all()
    return render_template('marketplace/landing-page.html', form=form, categories=categories_instances, featured_products=featured_products,
                           new_arrived_products=new_arrived_products, settings=settings, website_settings=website_settings, brands=brands, banner=banner,
                           background=background, logo=logo)


@marketplace.route('/review', methods=['POST'])
def review():
    product_id = int(request.form.get('product_id'))
    product_name = request.form.get('product_name')
    review_text = request.form.get('review_text')
    review_rating = float(request.form.get('review_rating'))
    product_instance = MProduct.query.get_or_404(product_id)
    review = MReview(message=review_text, score=review_rating,
                     user=current_user, product=product_instance)
    db.session.add(review)
    db.session.commit()
    return {
        "status": 1
    }

#'''
# This view is not really necessary.
@marketplace.route('/categories')
def categories():
    categories_list = MCategory.query.filter_by(parent_id=None).all()
    website_settings = MSettings.query.first()
    return render_template('marketplace/categories/index.html', website_settings=website_settings, categories=categories_list)
#'''

@marketplace.route('/category/<int:category_id>/<category_name>', defaults={'page': 1}, methods=['GET'])
@marketplace.route('/category/<int:category_id>/<category_name>/<int:page>', methods=['GET'])
@marketplace.route('/category/<int:category_id>/<category_name>/<int:page>', methods=['GET'])
def category(page, category_id, category_name):
    products = MProduct.query.join(MProductCategory).filter(
        MProductCategory.category_id == category_id).paginate(page, per_page=8)
    website_settings = MSettings.query.first()
    return render_template('marketplace/categories/category.html', website_settings=website_settings, category_id=category_id, category_name=category_name, products=products)


@marketplace.route('/product/<int:product_id>/<product_name>')
def product(product_id, product_name):
    product_instance = db.session.query(MProduct).filter(
        MProduct.id == product_id).options(joinedload(MProduct.variants)).first()
    product_variants = product_instance.variants
    review_form = ReviewForm()
    # print(current_user.name)
    if current_user.is_authenticated:
        current_user_review = MReview.query.filter_by(
            user=current_user).filter_by(product=product_instance).first()
    website_settings = MSettings.query.first()
    # if current_user.is_authenticated and current_user.is_seller:
    #     can_review = False
    # elif current_user.is_authenticated and current_user_review:
    #     can_review = False
    # elif current_user.is_authenticated and not current_user_review:
    #     can_review = True
    # else:
    #     can_review = False
    can_review = True if current_user.is_authenticated and not current_user_review else False

    settings = LandingSetting.query.all()
    return render_template('marketplace/products/product.html', website_settings=website_settings, review_form=review_form,
                           can_review=can_review, product_instance=product_instance, settings=settings)


@marketplace.route('/seller/<int:seller_id>/products')
def view_seller_products(seller_id):
    seller = User.query.filter_by(id=seller_id).filter_by(
        is_seller=True).first_or_404()
    avail_products = MProduct.query.filter_by(
        seller=seller).filter_by(availability=True).all()
    not_avail_products = MProduct.query.filter_by(
        seller=seller).filter_by(availability=False).all()
    website_settings = MSettings.query.first()
    return render_template('marketplace/products/seller.html', website_settings=website_settings, avail_products=avail_products,
                           not_avail_products=not_avail_products)


@marketplace.route('/cart')
def cart():
    cart_instance = get_current_cart()
    website_settings = MSettings.query.first()
    if cart_instance.products_count == 0:
        cart_instance.step = 1
        return render_template('marketplace/cart/no_items.html', website_settings=website_settings)
    if cart_instance.step != 1:
        return redirect(url_for('marketplace.order', step=cart_instance.step))
    return render_template('marketplace/cart/index.html', website_settings=website_settings, cart=cart_instance)


@marketplace.route('/order/<int:step>', methods=['GET', 'POST'])
def order(step):
    cart_instance = get_current_cart()
    website_settings = MSettings.query.first()
    if cart_instance.products_count == 0:
        cart_instance.step = 1
        return render_template('marketplace/cart/no_items.html', website_settings=website_settings)

    if request.method == 'POST':
        if step == 1:
            cart_instance.step = 1
            return redirect(url_for('marketplace.cart'))

        elif step == 2:
            print("Enter your details")
            if cart_instance.step == 1:
                for item in cart_instance.cart_items:
                    product_instance = item.product
                    if item.count < product_instance.min_order_quantity:
                        flash("You cannot buy less than {} pieces of the product {}".format(
                            product_instance.min_order_quantity, product_instance.name), 'error')
                        return redirect(url_for('marketplace.cart'))
                cart_instance.step = 2
                return redirect(url_for('marketplace.order', step=2))

            if cart_instance.step == 3:
                cart_instance.step = 2
                MCartDetails.query.filter_by(cart=cart_instance).delete()
                items = MCartItem.query.filter_by(cart=cart_instance).all()
                for item in items:
                    item.shipping_method = None
                    db.session.add(item)
                db.session.commit()
                return redirect(url_for('marketplace.order', step=2))

            if cart_instance.step == 2:
                return redirect(url_for('marketplace.order', step=2))

        elif step == 3:
            print("Now enter your stripe")
            form = SShippingForm()
            valid = True
            for seller_cart in cart_instance.seller_carts:
                input_field = "shipping[{}]".format(seller_cart.seller.id)
                val = request.form.get(input_field)
                if not val:
                    valid = False
                    form.errors[input_field] = ['This Field is Required']
                elif not MShippingMethod.query.get(val):
                    form.errors[input_field] = [
                        'Not A Valid Choice, Pls Try Again']
                    valid = False
            if not current_user.is_authenticated:
                user = User.query.filter_by(email=form.email.data).first()
                if user:
                    flash(
                        'There is a mediville user with this email, choose another email or login instead', 'error')
                    valid = False
            if not valid:
                form.process(request.form)
                return render_template('marketplace/cart/order_shipping.html', cart=cart_instance, form=form, website_settings=website_settings)

            if form.validate_on_submit():
                cart_details = MCartDetails(
                    cart=cart_instance,
                    first_name=form.first_name.data,
                    last_name=form.last_name.data,
                    email=form.email.data,
                    mobile_phone=form.mobile_phone.data,
                    state=form.state.data,
                    zip=form.zip.data,
                    country=form.country.data,
                    city=form.city.data,
                )

flask-marketplace/marketplace/app/templates/marketplace/index.html
{% extends 'layouts/base.html' %}
{% import 'macros/product_macros.html' as products_macros %}
{% block custom_head_tags %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lightbox/css/lightbox.min.css') }}">
    <style>
        .slick-prev:before, .slick-next:before {
            color: black;
        }
        .slick-prev {
            left: 0px;
            z-index: 100;
        }
        .slick-next {
            right: 0px;
            z-index: 100;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="ui stackable centered grid marketplace container">
        <div class="sixteen wide column">
            <h1 class="ui header">
                Market Place
            </h1>
            <h2 class="ui header">
                Featured Products
            </h2>
            <hr>
            <div class="ui centered cards">
                {% for product in products %}
                    {{ products_macros.product_wid(product) }}
                {% endfor %}
            </div>
            <hr>
            <h2 class="ui header">
                Featured Categories
            </h2>
            <hr>
            <div class="ui link centered cards">
                {% for category in categories %}
                    {{ products_macros.category_wid(category) }}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='lightbox/js/lightbox.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.slick').slick({
                infinite: false,
            });
        });

    </script>
{% endblock %}

flask-marketplace/marketplace/app/templates/marketplace/landing-page.html
{% extends 'layouts/ecommerce_base.html' %}
{% import 'macros/category_macros.html' as category_macros %}
{% import 'macros/product_macros.html' as products_macros %}
{% import 'macros/brand_macros.html' as brand_macros %}


{% block content %}
<nav class="navbar navbar-main navbar-expand-lg navbar-light border-bottom" style="margin-bottom: 20px !important;">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse show" id="main_nav">
      <ul class="navbar-nav">
      	<li class="nav-item ">
          <a class="nav-link pl-0" href="{{url_for('marketplace.categories')}}">
            <strong>
              <i class="fa fa-bars"></i> &nbsp;  All category
            </strong>
          </a>
        </li>
          {% for category in categories %}
              {{ category_macros.category_wid(category) }}
          {% endfor %}
      </ul>
    </div> 
  </div> 
</nav>


<!-- ========================= SECTION INTRO ========================= -->
<section class="section-intro">
  <div class="container">
    <div class="intro-banner-wrap">
      <img src="{{ background.image_url }}">
    </div>
  </div>
</section>
  <!-- ========================= SECTION INTRO END// ========================= -->
  
  
  <!-- ========================= SECTION FEATURE ========================= -->
  <section class="section-content padding-y-sm">
  <div class="container">
  <article class="card card-body">
  
  
  <div class="row">
    <div class="col-md-4">	
      <figure class="item-feature">
        <!-- <span class="text-primary"><i class="fa fa-2x fa-truck"></i></span> -->
        <!---<img height="50" src="{# banner.image_url #}">--->
        <figcaption class="pt-3">
          <h5 class="title">{{ banner.feature_header_one }}</h5>
          <p>{{ banner.feature_description_one }}</p>
        </figcaption>
      </figure> <!-- iconbox // -->
    </div><!-- col // -->
    <div class="col-md-4">
      <figure  class="item-feature">
        <!-- <span class="text-primary"><i class="fa fa-2x fa-landmark"></i></span>	 -->
        <!---<img height="50" src="{# url_for('_uploads.uploaded_file', setname='images',
        filename=banner.feature_icon_two , _external=True) #}">--->
        <figcaption class="pt-3">
          <h5 class="title">{{ banner.feature_header_two }}</h5>
          <p>{{ banner.feature_description_two }}</p>
        </figcaption>
      </figure> <!-- iconbox // -->
    </div><!-- col // -->
      <div class="col-md-4">
      <figure  class="item-feature">
        <!-- <span class="text-primary"><i class="fa fa-2x fa-lock"></i></span> -->
        <!----<img height="50" src="{# url_for('_uploads.uploaded_file', setname='images',
        filename=banner.feature_icon_three , _external=True) #}">---> 
        <figcaption class="pt-3">
          <h5 class="title">{{ banner.feature_header_three }}</h5>
          <p>{{ banner.feature_description_three }}</p>
        </figcaption>
      </figure> <!-- iconbox // -->
    </div> <!-- col // -->
  </div>
  </article>
  
  </div> <!-- container .//  -->
  </section>
  <!-- ========================= SECTION FEATURE END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name">
  <div class="container">

    <header class="section-heading">
      <!-- <a href="#" class="btn btn-outline-primary float-right">See all</a> -->
      <h3 class="section-title">Featured products</h3>
    </header>
    <div class="row">
      {% for product in featured_products %}
        <div class="col-md-3">
          {{ products_macros.custom_product(product) }}
        </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- ========================= SECTION  END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name">
  <div class="container">

    <header class="section-heading">
      <!-- <a href="#" class="btn btn-outline-primary float-right">See all</a> -->
      <h3 class="section-title">New arrived</h3>
    </header>
    <div class="row">
      {% for product in new_arrived_products %}
        <div class="col-md-3">
          {{ products_macros.custom_product(product) }}
        </div>
      {% endfor %}
    </div>
  </div>
</section>
  <!-- ========================= SECTION  END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name bg padding-y-sm">
	<div class="container">
		<header class="section-heading">
			<h3 class="section-title">Our Brands</h3>
		</header><!-- sect-heading -->
		
		<div class="row">
			{% for brand in brands %}
				{{ brand_macros.brand_wid(brand) }}
			{% endfor %}
		</div> <!-- row.// -->
	</div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->
{% endblock %}

flask-marketplace/marketplace/app/templates/marketplace/page-index-1.html
{% import 'macros/category_macros.html' as category_macros %}
{% import 'macros/product_macros.html' as products_macros %}
{% import 'macros/brand_macros.html' as brand_macros %}
{% import 'macros/footer_macros.html' as footer %}
{% import 'macros/header_macros.html' as header %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="cache-control" content="max-age=604800" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

{% if settings %}
<title>{{ settings.title }}</title>
<meta name="description"
          content="{{ settings.description }}">
<meta name="author" content="{{ settings.title }}">
<meta name="og:title" content="{{ settings.title }}"/>
<meta name="og:type" content="website"/>
<meta name="og:url" content="https://www.{{ settings.title }}"/>
<meta name="og:image" content="{{ background.image_url }}"/>
<meta name="og:site_name" content="{{ settings.title }}"/>
<meta name="og:description"
          content="{{ settings.description }}"/>
<meta name="twitter:card" content="summary"/>
<meta name="twitter:site" content="@{{ settings.title }}"/>
<meta name="twitter:creator" content="@{{ config.APP_NAME }}"/>
<meta property="og:url" content="https://www.{{ config.APP_NAME }}"/>
<meta property="og:title" content="{{ settings.title }}"/>
<meta property="og:description"
          content="{{ settings.description }}"/>
<meta property="og:image" content="{{ background.image_url }}"/>
{% endif %}




<link href="{{ url_for('static', filename='images/favicon.ico') }}" rel="shortcut icon" type="image/x-icon">

<!-- jQuery -->
<script src="{{ url_for('static', filename='js/jquery-2.0.0.min.js') }}" type="text/javascript"></script>

<!-- Bootstrap4 files-->
<script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}" type="text/javascript"></script>
<link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet" type="text/css"/>

<!-- Font awesome 5 -->
<link href="{{ url_for('static', filename='fonts/fontawesome/css/all.min.css') }}" type="text/css" rel="stylesheet">

<!-- custom style -->
<link href="{{ url_for('static', filename='css/ui.css') }}" rel="stylesheet" type="text/css"/>
<link href="{{ url_for('static', filename='css/responsive.css') }}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

<!-- custom javascript -->
<script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>


{% if settings.google_analytics_id %}
{{settings.google_analytics_id |safe}}
{% endif %}
{% if settings.other_tracking_analytics_one %}
{{settings.other_tracking_analytics_one | safe}}
{% endif %}
{% if settings.other_tracking_analytics_two %}
{{settings.other_tracking_analytics_two | safe}}
{% endif %}

{% if settings.other_tracking_analytics_three %}
{{settings.other_tracking_analytics_three | safe}}
{% endif %}

{% if settings.other_tracking_analytics_four %}
{{settings.other_tracking_analytics_four | safe}}
{% endif %}


<script type="text/javascript">
/// some script

// jquery ready start
$(document).ready(function() {
	// jQuery code

}); 
// jquery end
</script>

</head>
<body>


<header class="section-header">
{{ header.header_macro(current_user, website_settings) }}
<section class="header-main border-bottom">
	<div class="container">
<div class="row align-items-center">
	<div class="col-lg-2 col-6">
		<a href="{{url_for('marketplace.index')}}" class="brand-wrap">
			<img class="logo" src="{{ logo.image_url }}">
		</a> <!-- brand-wrap.// -->
	</div>
	<div class="col-lg-6 col-12 col-sm-12">
		<form action="{{ url_for('main.search', query=0) }}">
			<div class="input-group w-100">
				{{ form.query(class_="form-control") }}
			    <div class="input-group-append">
			      <button class="btn btn-primary" type="submit">
			        <i class="fa fa-search"></i>
			      </button>
			    </div>
			</div>
		</form>
	</div> <!-- col.// -->
	<div class="col-lg-4 col-sm-6 col-12">
		<div class="widgets-wrap float-md-right">
			<div class="widget-header  mr-3">
				<a href="{{url_for('marketplace.cart')}}" class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></a>
				<span class="badge badge-pill badge-danger notify">0</span>
			</div>
			<div class="widget-header icontext">
				<a href="{{url_for('account.profile')}}" class="icon icon-sm rounded-circle border"><i class="fa fa-user"></i></a>
				<div class="text">
					<span class="text-muted">Welcome!</span>
					{% if current_user.is_authenticated %}
					<div> 
						{{ current_user.full_name }} |
						<a href="{{url_for('account.logout')}}">Log out</a> 
					</div>
					{% else %}
					<div> 
						<a href="{{url_for('account.login')}}">Sign in</a> |  
						<a href="{{url_for('account.register')}}"> Register</a>
					</div>
					{% endif %}
				</div>
			</div>
		</div> <!-- widgets-wrap.// -->
	</div> <!-- col.// -->
</div> <!-- row.// -->
	</div> <!-- container.// -->
</section> <!-- header-main .// -->
</header> <!-- section-header.// -->

<nav class="navbar navbar-main navbar-expand-lg navbar-light border-bottom">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="main_nav">
      <ul class="navbar-nav">
      	<li class="nav-item dropdown">
          <a class="nav-link pl-0" data-toggle="dropdown" href="#"><strong> <i class="fa fa-bars"></i> &nbsp  All category</strong></a>
        </li>
		{% for category in categories %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('marketplace.category', category_id=category.id, category_name=category.name ) }}">{{category.name}}</a>
        </li>
		{% endfor %}
      </ul>
    </div> <!-- collapse .// -->
  </div> <!-- container .// -->
</nav>

</header> <!-- section-header.// -->



<!-- ========================= SECTION INTRO ========================= -->
<section class="section-intro padding-y-sm">
<div class="container">

{% if background %}
<div class="intro-banner-wrap">
	<img src="{{ background.image_url}}" class="img-fluid rounded">
</div>
{% endif %}
</div> <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

{% if features %}
<!-- ========================= SECTION FEATURE ========================= -->
<section class="section-content padding-y-sm">
<div class="container">
<article class="card card-body">
<div class="row">
{% for feature in features %}
	<div class="col-md-4">	
		<figure class="item-feature">
			<span class="text-primary"><i class="fa fa-2x fa-{{ feature.icon}}"></i></span>
			<figcaption class="pt-3">
				<h5 class="title">{{ feature.title}}</h5>
				<p>{{ feature.description }} </p>
			</figcaption>
		</figure> <!-- iconbox // -->
	</div><!-- col // -->
{% endfor %}
</div>
</article>

</div> <!-- container .//  -->
</section>
<!-- ========================= SECTION FEATURE END// ========================= -->
{% endif %}


<!-- ========================= SECTION  ========================= -->
<section class="section-name">
  <div class="container">

    <header class="section-heading">
      <!-- <a href="#" class="btn btn-outline-primary float-right">See all</a> -->
      <h3 class="section-title">Featured products</h3>
    </header>
    <div class="row">
      {% for product in featured_products %}
        <div class="col-md-3">
          {{ products_macros.custom_product(product) }}
        </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- ========================= SECTION  END// ========================= -->

<!-- ========================= SECTION  ========================= -->
<section class="section-name">
  <div class="container">

    <header class="section-heading">
      <!-- <a href="#" class="btn btn-outline-primary float-right">See all</a> -->
      <h3 class="section-title">New arrived</h3>
    </header>
    <div class="row">
      {% for product in new_arrived_products %}
        <div class="col-md-3">
          {{ products_macros.custom_product(product) }}
        </div>
      {% endfor %}
    </div>
  </div>
</section>
  <!-- ========================= SECTION  END// ========================= -->
{% if brands %}
<!-- ========================= SECTION  ========================= -->
<section class="section-name bg padding-y-sm">
	<div class="container">
		<header class="section-heading">
			<h3 class="section-title">Our Brands</h3>
		</header><!-- sect-heading -->
		
		<div class="row">
			{% for brand in brands %}
				{{ brand_macros.brand_wid(brand) }}
			{% endfor %}
		</div> <!-- row.// -->
	</div><!-- container // -->
</section>
<!-- ========================= SECTION  END// ========================= -->
{% endif %}


<!-- ========================= SECTION  ========================= -->
<!---<section class="section-name padding-y">
<div class="container">

<h3 class="mb-3">Download app demo text</h3>

<a href="#"><img src="images/misc/appstore.png" height="40"></a>
<a href="#"><img src="images/misc/appstore.png" height="40"></a>

</div><!-- container // -->
<!--</section>---->
<!-- ========================= SECTION  END// ======================= -->

{{ footer.footer_macro(current_user, website_settings) }}



</body>
</html>