flask-marketplace/marketplace/app/blueprints/main/forms.py
from app.models import *
from flask_ckeditor import CKEditorField
from flask_uploads import UploadSet, IMAGES
from flask_wtf import Form, FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import IntegerField, StringField, SubmitField, DateField, TextAreaField, FormField, MultipleFileField, \
    RadioField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Length, Required, ValidationError, InputRequired, Email

images = UploadSet('images', IMAGES)
docs = UploadSet('docs', ('rtf', 'odf', 'ods', 'gnumeric', 'abw', 'doc', 'docx', 'xls', 'xlsx', 'pdf'))


class TelephoneForm(FlaskForm):
    country_code = IntegerField('Country Code', validators=[Required()])
    area_code = IntegerField('Area Code/Exchange', validators=[Required()])
    number = StringField('Number')


class ContactForm(FlaskForm):
    first_name = StringField()
    last_name = StringField()
    mobile_phone = FormField(TelephoneForm)
    office_phone = FormField(TelephoneForm)


class PhotoForm(FlaskForm):
    photo = FileField('Image file', validators=[FileRequired(), FileAllowed(images, 'Images only!')])
    submit = SubmitField('Submit')


class TagForm(FlaskForm):
    tag = StringField('Please tag your question', validators=[DataRequired()])



class AnswerForm(FlaskForm):
    """ This is the question answers form  """
    body = TextAreaField('Answers', validators=[DataRequired(), Length(min=2, max=5000)])
    submit = SubmitField('Answer')


class MessageForm(FlaskForm):
    message = StringField(('Message'), validators=[
        DataRequired(), Length(min=1, max=2500)])
    submit = SubmitField(('Submit'))


# class MessageForm(FlaskForm):
#     """ This is the messageform  """
#     body = TextAreaField('Message', validators=[Required(), Length(min=50, max=5000)])
#     submit = SubmitField('Submit')
#
# class ReplyForm(FlaskForm):
#     """ This is the message reply form  """
#     body = TextAreaField('Reply', validators=[Required(), Length(min=50, max=5000)])
#     submit = SubmitField('Submit')


class PostForm(FlaskForm):
    # image = FileField('Image', validators=[FileRequired(), FileAllowed(images, 'Images only!')])
    text = TextAreaField('')
    photo = MultipleFileField('Add Photos', validators=[FileAllowed(images, 'Images only!')])
    post_privacy = RadioField('Privacy', choices=[('0', 'Everyone'), ('1', 'Followers Only'), ('2', 'Private')],
                              default='0')
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    """ This is the comments form  """
    body = TextAreaField('Comments', validators=[DataRequired(), Length(min=50, max=5000)])
    submit = SubmitField('Submit')


class InviteUserForm(FlaskForm):
    first_name = StringField(
        'First name', validators=[InputRequired(),
                                  Length(1, 64)])
    last_name = StringField(
        'Last name', validators=[InputRequired(),
                                 Length(1, 64)])
    email = EmailField(
        'Email', validators=[InputRequired(),
                             Length(1, 64),
                             Email()])
    submit = SubmitField('Invite')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered.')

flask-marketplace/marketplace/app/blueprints/main/__init__.py
from app.blueprints.main import errors  # noqa
from app.blueprints.main.views import main  # noqa

flask-marketplace/marketplace/app/blueprints/main/views.py
import operator

from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
from flask_sqlalchemy import Pagination
from sqlalchemy import desc, func
from app.email import send_email
from .forms import *
from app.blueprints.marketplace.forms import SearchForm
from ...utils import Struct
#from app.models import MSettings, MBanner, BackgroundImage, LandingSetting, SiteLogo, MProduct, MCategory

main = Blueprint('main', __name__)
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS



@main.route('/')
def index():
    form = SearchForm()
    banner = MBanner.query.first()
    background = BackgroundImage.query.first()
    logo = SiteLogo.query.first()
    settings = LandingSetting.query.first()
    website_settings = MSettings.query.first()
    brands = MBrand.query.order_by(MBrand.created_at.asc()).limit(5).all()
    featured_products = MProduct.query.filter_by(availability=True).filter_by(
        is_featured=True).order_by(MProduct.created_at.asc()).limit(4).all()  # .limit(5).all()
    new_arrived_products = MProduct.query.filter_by(
        availability=True).order_by(MProduct.created_at.desc()).limit(4).all()
    featured_categories = MCategory.query.filter_by(is_featured=True).all()
    categories = MCategory.query.limit(6).all()
    features = Feature.query.limit(3).all()
    products = MProduct.query.limit(4).all()
    return render_template('marketplace/page-index-1.html', form=form, featured_categories=featured_categories, categories=categories, featured_products=featured_products,
                           new_arrived_products=new_arrived_products, settings=settings, website_settings=website_settings, brands=brands, banner=banner,
                           background=background, logo=logo, features=features, products=products)


@main.route('/search')
def search():
    website_settings = MSettings.query.first()

    query = request.args.get('query')
    page = request.args.get('page')
    search_type = request.args.get('type')
    sort_by = request.args.get('sort_by')
    sort_dir = request.args.get('sort_dir')


    query = query if query is not None else ''
    page = page if page is not None else 1
    try:
        page = int(page)
    except:
        page = 1
    search_type = search_type if search_type is not None else ''
    sort_by = sort_by if sort_by is not None else ''
    sort_dir = sort_dir if sort_dir is not None else ''
    if len(query) < 3:
        flash("Search Query must be at least 3 characters", "error")
        return render_template("main/search_results.html", website_settings=website_settings, query=query, search_type=search_type, sort_by=sort_by,
                               sort_dir=sort_dir, results=[])
    results = []
    if search_type == '':
##        job_results = Job.query.whooshee_search(query, order_by_relevance=0).all()
##        user_results = User.query.whooshee_search(query, order_by_relevance=0).all()
##        questions_results = Question.query.whooshee_search(query, order_by_relevance=0).all()
        products_results = MProduct.query.whooshee_search(query).all()

##        job_results_count = Job.query.whooshee_search(query, order_by_relevance=0).count()
##        user_results_count = User.query.whooshee_search(query, order_by_relevance=0).count()
##        questions_results_count = Question.query.whooshee_search(query, order_by_relevance=0).count()
        products_results_count = MProduct.query.whooshee_search(query, order_by_relevance=0).count()

##        all_results = job_results + user_results + questions_results + products_results
##        all_count = job_results_count + user_results_count + questions_results_count + products_results_count
        all_results = products_results
        all_count = products_results_count
        results = sorted(all_results, key=operator.attrgetter("score"))
        results.reverse()
        results = results[(page-1)*40:page*40]
        paginator = Pagination(items=results, page=page, per_page=40, query=None, total=all_count)
        results = paginator

##    elif search_type == 'people':
##        results = User.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
##        # results = sorted(user_results, key=operator.attrgetter("score"))
##    elif search_type == 'jobs':
##        results = Job.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
##        # results = sorted(job_results, key=operator.attrgetter("score"))
##    elif search_type == 'questions':
##        results = Question.query.whooshee_search(query, order_by_relevance=-1).paginate(page, per_page=40)
##        # results = sorted(questions_results, key=operator.attrgetter("score"))
    elif search_type == 'products':
        results = MProduct.query.whooshee_search(query, order_by_relevance=10).paginate(page, per_page=8)
        # results = sorted(products_results, key=operator.attrgetter("score"))

    
    return render_template("main/search_results.html", website_settings=website_settings, query=query, search_type=search_type, sort_by=sort_by,
                           sort_dir=sort_dir, results=results)




@main.route('/profile', methods=['GET', 'POST'])
def profile():
    return redirect(url_for('account.profile'))


@main.route('/list/', defaults={'page': 1})
@main.route('/list/page/<int:page>', methods=['GET'])
@login_required
def select_section(page):
    website_settings = MSettings.query.first()
    paginated = User.query.filter(User.id != current_user.id).order_by(User.id.desc()).paginate(page, per_page=25)
    return render_template('main/selection.html', paginated=paginated, website_settings=website_settings)


@main.route('/profile/<int:user_id>/', methods=['GET'], defaults={'active': 'posts', 'page': 1})
@main.route('/profile/<int:user_id>/<active>', methods=['GET'], defaults={'page': 1})
@main.route('/profile/<int:user_id>/<active>/page/<page>', methods=['GET'])
def user_detail(user_id, active, page):
    website_settings = MSettings.query.first()
    """Provide HTML page with all details on a given user """
    user = User.query.get_or_404(user_id)
    if active == 'posts':
        items = user.posts.paginate(page, per_page=10)
    elif active == 'questions':
        items = user.questions.paginate(page, per_page=10)
    else:
        items = []
    user_id = Photo.user_id
    photo = Photo.query.filter_by(id=user_id).limit(1).all()
    return render_template('public/profile.html', website_settings=website_settings, user=user, current_user=current_user, photo=photo, id=User.id,
                           items=items)


@main.route('/user/<int:id>/<full_name>', defaults={'active': 'posts', 'page': 1})
@main.route('/user/<int:id>/<full_name>/<active>', defaults={'page': 1})
@main.route('/user/<int:id>/<full_name>/<active>/page/<int:page>')
@login_required
def user(id, full_name, active, page):
    website_settings = MSettings.query.first()
    user = db.session.query(User).filter(User.id == id, User.full_name == full_name).first()
    edit_form = PostForm()
    if user == current_user:
        return redirect(url_for('main.profile', active=active))
    return render_template('main/profile.html', website_settings=website_settings, user=user, edit_form=edit_form)  # , photo=photo)


@main.route('/photo/upload', methods=['GET', 'POST'])
@login_required
def photo_upload():
    website_settings = MSettings.query.first()
    ''' check if photo already exist, if it does, send to homepage. Avoid duplicate upload here'''
    check_photo_exist = db.session.query(Photo).filter(Photo.user_id == current_user.id).count()
    if check_photo_exist >= 1:
        pass
        # return redirect(url_for('main.index'))
    form = PhotoForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            image_filename = images.save(request.files['photo'])
            image_url = images.url(image_filename)
            picture_photo = Photo.query.filter_by(user_id=current_user.id).first()
            if not picture_photo:
                picture_photo = Photo(
                    image_filename=image_filename,
                    image_url=image_url,
                    user_id=current_user.id,
                )
            else:
                picture_photo.image_filename = image_filename
                picture_photo.image_url = image_url
            db.session.add(picture_photo)
            db.session.commit()
            flash("Image saved.")
            return redirect(url_for('main.index'))
        else:
            flash('ERROR! Photo was not saved.', 'error')
    return render_template('main/upload.html', website_settings=website_settings, form=form)


@main.route('/invite-colleague', methods=['GET', 'POST'])
@login_required
def invite_user():
    website_settings = MSettings.query.first()
    """Invites a new user to create an account and set their own password."""

    form = InviteUserForm()
    if form.validate_on_submit():
        invited_by = db.session.query(User).filter_by(id=current_user.id).first()
        user = User(
            invited_by=invited_by.full_name,
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data)
        db.session.add(user)
        db.session.commit()
        token = user.generate_confirmation_token()
        invite_link = url_for(
            'account.join_from_invite',
            user_id=user.id,
            token=token,
            _external=True)

        get_queue().enqueue(
            send_email,
            recipient=user.email,
            subject='You Are Invited To Join',
            template='account/email/invite',
            user=user.id,
            invited_by=invited_by,
            invite_link=invite_link,
            invite_by=invited_by

flask-marketplace/marketplace/app/templates/main/allquestions.html
{% extends 'layouts/base.html' %}
{% import 'macros/allquestion_macros.html' as question_wid %}

{% block content %}
    <div class="ui two column centered grid">
        <div class="column">
            <h1>Available questions</h1>
        </div>
    </div>
    <div class="ui grid">
        <div class="four wide column"></div>
        <div class="eight wide column">
            <div class="ui cards">
                {% for question in appts %}
                    {{ question_wid.question_wid(question) }}
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

flask-marketplace/marketplace/app/templates/main/create_question.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/answer_macros.html' as traverse %}
{% import 'macros/job_macros.html' as job_wid %}
{% import 'macros/follow_macros.html' as follow %}

{% block custom_head_tags %}
    <style>
        .display-none {
            display: none;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="ui grid container" id="example3">
        <div class="eight wide computer sixteen wide mobile centered column">

            {% set flashes = {
		'error':   get_flashed_messages(category_filter=['form-error']),
		'warning': get_flashed_messages(category_filter=['form-check-email']),
		'info':    get_flashed_messages(category_filter=['form-info']),
		'success': get_flashed_messages(category_filter=['form-success'])
		} %}

            {{ f.begin_form(form, flashes) }}
            <div class="ui grid">
                <div class="computer only row">
                    <div class="left ui rail">
                        <p></p>
                        <div class="ui sticky">
                            <h3 class="ui header">Colleagues to follow</h3>
                            <div class="ui divided items">
                                {% for user in follow_lists %}
                                    {{follow.follow_wid(user, current_user)}}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                    <div class="right ui right rail">
                        <div class="ui sticky">
                            <div class="ui cards">
                                {% for job in jobs %}
                                    {{ job_wid.job_wid(job) }}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="ui grid">
                <div class="mobile only tablet only row">
                    <br>
                </div>
            </div>
            <div class="ui segment">
                <div class="ui form">
                    <form>
                        <div class="field">
                            {{ f.render_form_field(form.title) }}
                        </div>
                        <div class="field">
                            {{ f.render_form_field(form.description) }}
                        </div>

                        {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                        {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                        {{ f.form_message(flashes['info'], header='Information', class='info') }}
                        {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                        {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                            {{ f.render_form_field(field) }}
                        {% endfor %}
                    </form>
                </div>
            </div>

            {% for post in results %}
                <div class="ui fluid card">
                    <div class="extra content">
                        <h2 class="left floated ui header">
                            <a href="{{ url_for('main.user', id=post.user.id, full_name=post.user.full_name) }}">
                                <img class="left floated mini ui image" src="{{ post.user.get_photo() }}">
                            </a>
                            <span class="post-head">
                                <a href="{{ url_for('main.user', id=post.user.id, full_name=post.user.full_name) }}">
                                    {{ post.user.full_name }}</a>
                                <small class="very-small">
                                    <a href="{{ url_for('main.question_details', question_id=post.id, title=post.title ) }}">{{ post.created_at.strftime("%b %d, %Y at %H:%I:%S") }}</a>
                                </small>
                            </span>
                        </h2>

                        {% if post.user.id == current_user.id %}
                            <p class="options btn" style="cursor: pointer">
                                <i class="large ellipsis vertical icon right floated" style="margin-right: -0.5rem;">
                                </i>
                            </p>
                            <div class="ui special popup" style="margin-right: -1rem;margin-top: 2rem;padding-left: 1px;padding-right: 1px; padding-bottom: 1px">
                                <ul style="list-style-type: none;padding:0;margin-bottom: 1px;margin-top: 0">
                                    <li class="item" style="padding: 5px 35px 3px 15px"
                                        onclick='editQuestion("{{ post.id }}", {{ post.title | tojson  }}, {{ post.description | tojson }})'>
                                        <a href="#">Edit Question</a>
                                    </li>
                                    <li class="item" style="padding: 5px 35px 3px 15px" onclick='deleteQuestion("{{ post.id }}")'>
                                        <a href="#">Delete Question</a>
                                    </li>
                                </ul>
                            </div>
                        {% endif %}

                    </div>
                    <div class="content">
                        <div class="header">
                            <a href="{{ url_for('main.question_details', question_id=post.id, title=post.title ) }}">{{ post.title }}</a>
                        </div>
                        <div class="meta">
                            <span class="right floated time">{{ moment(post.timestamp).fromNow() }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

        <div class="ui grid">
            <div class="mobile only tablet only row">
                <button class="circular ui huge blue icon floating action button">
                    <i class="large white icon tasks"></i>
                </button>

                <div class="ui right sidebar inverted  menu">
                    <div class="ui padded grid">
                        <div class="ui cards">
                            {% for job in jobs %}
                                {{ job_wid.job_wid(job) }}
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="pusher">
                    <!-- Site content !-->
                </div>

            </div>
        </div>

    </div>

    {% include 'partials/_question_modals.html' %}

{% endblock %}
{% block scripts %}
    <script>
        $('.ui.sticky')
            .sticky({
                offset: 50,
                bottomOffset: 50,
                context: '#example3'
            })
        ;
    </script>

    <script>
        $(function () {
            $('.ui.button').on('submit', function (event) {
                $.ajax({
                    data: {body: $('reply').val()},
                    type: 'POST',
                    url: '/answer'
                });
                event.preventDefault();
            });
        });

        function toggleAnswer(answer_id) {
            $('#answer-' + answer_id).toggleClass('display-none');
        }
    </script>
{% endblock %}

flask-marketplace/marketplace/app/templates/main/more_notifications.html
                        {% for notification in notifications %}
                            <div class="item conversation-holder {% if notification.read != true %} not-read {% endif %}" onclick="location.href='{{ notification.link }}';">
                                <img class="ui avatar image" src="{{ notification.user.get_photo() }}">
                                <div class="content">
                                    {{ notification.text | safe }}
                                </div>
                                <div class="header">{{ notification.timestamp }}</div>
                            </div>
                        {% endfor %}

flask-marketplace/marketplace/app/templates/main/new_user.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}
{% import 'macros/check_password.html' as check %}

{% block scripts %}
{% endblock %}

{% block content %}
    <div class="ui stackable centered grid container">
        <div class="twelve wide column">
            <a class="ui basic compact button" href="{{ url_for('organisations.org_home') }}">
                <i class="caret left icon"></i>
                Back to dashboard
            </a>
            <h2 class="ui header">
                Add Colleague
                <div class="sub header">Send an invite to your colleague.</div>
            </h2>

            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

            <div class="two fields">
                {{ f.render_form_field(form.first_name) }}
                {{ f.render_form_field(form.last_name) }}
            </div>

            {{ f.render_form_field(form.email) }}

            {% if form.password %}

                <div class="two fields">
                    {{ f.render_form_field(form.password) }}
                    {{ f.render_form_field(form.password2) }}
                </div>

            {% endif %}

            {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
            {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
            {{ f.form_message(flashes['info'], header='Information', class='info') }}
            {{ f.form_message(flashes['success'], header='Success!', class='success') }}

            {% for field in form | selectattr('type', 'equalto', 'SubmitField') %}
                {{ f.render_form_field(field) }}
            {% endfor %}

            {{ f.end_form() }}
            {% if form.password %}
                {{ check.password_check('password', 0) }}
            {% endif %}
        </div>
    </div>
{% endblock %}

flask-marketplace/marketplace/app/templates/main/search_results.html
{% extends 'layouts/base.html' %}
{% import 'macros/product_macros.html' as products_macros %}
{% block custom_head_tags %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='lightbox/css/lightbox.min.css') }}">
    <style>
        .slick-prev:before, .slick-next:before {
            color: black;
        }
        .slick-prev {
            left: 0px;
            z-index: 100;
        }
        .slick-next {
            right: 0px;
            z-index: 100;
        }

    </style>
{% endblock %}
{% block content %}
    <div class="ui stackable centered grid container">
        <div class="sixteen wide column">
            <h2 class="ui header">
                Search
                <span class="sub header">Search results for '{{ query }}'.</span>
            </h2>
            <form class="ui inline form fluid" style="width: 100%" method="GET" action="{{ url_for('main.search') }}">
                <div class="fields" style="margin-bottom: 0">
                    <div class="fourteen wide field">
                        <input type="text" name="query"  placeholder="Search across platform" value="{{ query }}" required autocomplete minlength="3">
                    </div>
                    <div class="two wide field">
                        <button type="submit" class="ui button" style="width: 100%"><i class="search icon"></i></button>
                    </div>
                </div>
            </form>
        </div>
        <div class="four wide column">
            <div class="ui vertical fluid tabular menu">
                <a class="{% if search_type == '' %} active {% endif %}item" href="{{ url_for('main.search') }}?query={{ query }}&type=&sort_by={{ sort_by }}&sort_dir={{ sort_dir }}">
                    <i class="home icon"></i>All Results
                </a>
                <a class="{% if search_type == 'products' %} active {% endif %}item" href="{{ url_for('main.search') }}?query={{ query }}&type=products&sort_by={{ sort_by }}&sort_dir={{ sort_dir }}">
                    <i class="shopping basket icon"></i>Marketplace products
                </a>
            </div>
        </div>
        <div class="twelve wide column">
            {% if results.total != 0 %}
                <div class="ui centered grid " style="overflow: hidden">
                    <br>

                    <hr>
                </div>
				{% else %}
            {% endif %}
            {% if results.items | length == 0 %}
                <br>
                <br>
                <br>
                <div class="ui very padded container centered grid">
                    <p class="ui grey label">No Results where found , please change the search query and try again...</p>
                </div>
            {% endif %}
            <div class="ui computer only grid ">

                {% for result in results.items %}
                    {% if result | product %}
                    <div class="col-md-4">
                        {{ products_macros.custom_product(result) }}
                    </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="ui tablet only grid  two cards">
                {% for result in results.items %}
                    {% if result | product %}
                        {{ products_macros.custom_product(result) }}
                    {% endif %}
                {% endfor %}
            </div>

            <div class="ui mobile only grid one cards">
                {% for result in results.items %}
                    {% if result | product %}
                        {{ products_macros.custom_product(result) }}
                    {% endif %}
                {% endfor %}
            </div>
            {% if results.items | length > 0 %}
                <div class="ui centered grid " style="overflow: hidden">
                    <div class="ui pagination menu">
                        {% for page in results.iter_pages() %}
                            {% if page %}
                                {% if page != results.page %}
                                    <a class="item" href="{{ url_for(request.endpoint) }}?page={{ page }}&query={{ query }}&type={{ type }}&sort_by={{ sort_by }}&sort_dir={{ sort_dir }}">
                                        {{ page }}
                                    </a>
                                {% else %}
                                    <a class="item active">
                                        {{ page }}
                                    </a>
                                {% endif %}
                            {% else %}
                                <div class="disabled item">
                                    ...
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <br>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {% include 'marketplace/partials/scripts.html' %}
    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='lightbox/js/lightbox.min.js') }}"></script>
    <script>
        $(document).ready(function () {
            $('.slick').slick({
                infinite: false,
            });
        });

    </script>
{% endblock %}